---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: flask-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: flask-app-conf          
                  key: REDIS_PORT
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: flask-app-conf          
                  key: REDIS_HOST
            
            - name: FLASK_PORT
              valueFrom:
                configMapKeyRef:
                  name: flask-app-conf          
                  key: FLASK_PORT
            - name: FLASK_HOST
              valueFrom:
                configMapKeyRef:
                  name: flask-app-conf          
                  key: FLASK_HOST
            
            - name: API_KEY
              valueFrom:
                configMapKeyRef:
                  name: flask-app-conf          
                  key: API_KEY
            
            - name: COIN_NAME
              valueFrom:
                configMapKeyRef:
                  name: flask-app-conf          
                  key: COIN_NAME
            
            - name: REDIS_TTL_SECS
              valueFrom:
                configMapKeyRef:
                  name: flask-app-conf          
                  key: REDIS_TTL_SECS
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask-app
  type: LoadBalancer