version: '3'
services:
    web-app:
        build: .
        ports:
            - "5000:5000"
        depends_on:
            - redis
        env_file:
          - .env
    redis:
        image: redis
        volumes:
          - redis-data:/data

volumes:
  redis-data: